# Name of WorkFlow which will be displayed in the Actions tab
name: CICD

# Manual click (delivery) whenever user wants
on:
  workflow_dispatch:
    inputs:
      environment: 
        description: This is the environment where the WorkFlow runs
        default: 'dev'
        required: true
        type: choice
        options:
          - dev
          - prod
          - staging
          
jobs:
# For every job there must be a seperate runner, it's called parallelism
  code:
    runs-on: ubuntu-latest
    steps:
       - name: checkout code
         run: echo "Code Clone from GitHub"

  build:
    needs: [code]
    runs-on: ubuntu-latest
    steps:
      - name: build docker container
        run: echo "Docker Container build"

  test:
    if: inputs.environment == 'dev'
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: test docker container
        run: echo " Testing the docker container"

  deploy:
    if: inputs.environment == 'dev'
    needs: [build, test]
    runs-on: ubuntu-latest
    steps:
      - name: deploy the app 
        run: echo "Docker compose deployed the app"
    
