# Name of WorkFlow which will be displayed in the Actions tab
name: CICD

# Manual click (delivery) whenever user wants
on:
  workflow_dispatch:
jobs:
# For every job there must be a seperate runner, it's called parallelism
  code:
    runs-on: ubuntu-latest
    steps:
       - name: checkout code
         run: echo "Code Clone from GitHub"

  build:
    needs: [code]
    runs-on: ubuntu-latest
    steps:
      - name: build docker container
        run: echo "Docker Container build"

  test:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: test docker container
        run: echo " Testing the docker container"

  deploy:
    needs: [build, test]
    runs-on: ubuntu-latest
    steps:
      - name: deploy the app 
        run: echo "Docker compose deployed the app"
    
